automation:
  - alias: Motion Lights — Living Room
    description: Motion-driven lighting for Living Room using eta-tier group; night mode, Variable bypass, sun elevation, restart-safe.
    id: motion_lights_living_room
    initial_state: true
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: hestia/library/templates/blueprints/sensor-light.yaml
      input:
        ambient_lux_entity: "sensor.living_room_multipurpose_alpha_illuminance"
        ambient_lux_threshold: 10
        bypass_entity: "{{ states('var.motion_bypass_living_room') == 'true' }}"
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.living_room_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""  # TODO
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.group_living_room_lights_all
        timeout_seconds: "{{ states('var.motion_timeout_living_room') | int(120) }}"
        transition_seconds: 0.3
