automation:
  - alias: Motion Lights — Wardrobe
    description: Motion-driven lighting for Wardrobe using eta-tier group; night mode, Variable bypass, sun elevation, restart-safe.
    id: motion_lights_wardrobe
    initial_state: true
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: hestia/library/templates/blueprints/sensor-light.yaml
      input:
        ambient_lux_entity: "" # TODO
        ambient_lux_threshold: 10
        bypass_entity: "{{ states('var.motion_bypass_wardrobe') == 'true' }}"
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.wardrobe_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: "" # TODO
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.group_wardrobe_light
        timeout_seconds: "{{ states('var.motion_timeout_wardrobe') | int(45) }}"
        transition_seconds: 0.3
