#═══════════════════════════════════════════════════════════════════
# ▶ HACS custom integration network_scanner ◀
# Loader: !include domain/rest/rest.yaml
# Schema: rest
# Home Assistant settings beyond configuration.yaml defined here.
# related: /config/hestia/library/ha_implementation/homeassistant/ha.split-configuration.md
#═══════════════════════════════════════════════════════════════════

homeassistant:
  name: "Hestia"
  latitude: 51.4623937
  longitude: -0.1289665
  time_zone: "Europe/London"
  unit_system: metric
  # Optimize startup sequence per ADR-0014 memory management
  safe_mode: false
  # Set reasonable timeouts for startup-blocking integrations (seconds)
  startup_timeout: 60

  customize_glob:
    sensor.gs724t_*:
      icon: mdi:ethernet
