############
# Configuration of Home Assistant. Contains the settings that
# did not make it into the configuration.yaml.
# https://www.home-assistant.io/docs/configuration/splitting_configuration/

homeassistant:
  name: "Hestia"
  latitude: 51.4623937
  longitude: -0.1289665
  time_zone: "Europe/London"
  unit_system: metric

