# File: /config/hestia/integrations/delijn.yaml
# Description: https://www.home-assistant.io/integrations/delijn/
# Created: 2025-06-11
# Version: 1.0

sensor:
  - platform: delijn
    api_key: !secret delijn_primary_key
    next_departure:
      - stop_id: '104225'
      - stop_id: '101285'
      - stop_id: '103753'
