automation:
  # Record Home Assistant restart time
  - id: record_ha_restart_time
    alias: "Record HA Restart Time"
    description: "Updates input_datetime helper with the exact restart time on Home Assistant startup."
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_ha_restart
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # Notify and set media state on Home Assistant start
  - id: d2d8775b-e666-4fb4-976d-02b4d9c5a396
    alias: Home Assistant Start - Notify
    description: "Notify user and set bedroom Sonos volume when HA starts."
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      # Notify via notification engine; includes timestamp from now()
      - service: script.notify_engine
        data:
          who: "evert"
          title: "HA started"
          value1: >
            Home Assistant started at {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
          group: ha
          tag_id: "information"
          importance_id: default
          color: "green"
          sticky: false
          timeout_sec: 300
      # Set Sonos to comfortable volume, only if player is available
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.bedroom_sonos_surround
                state_not: "unavailable"
            sequence:
              - service: media_player.volume_set
                target:
                  entity_id: media_player.bedroom_sonos_surround
                data:
                  volume_level: 0.3
        default: []
