# Authoritative; duplicate section removed on 18 August 2025.
line-length = 88
target-version = "py313"

[lint]
select = ["E","F","I","B","UP","SIM"]
ignore = ["E203"]  # Black compatibility on slicing whitespace
exclude = [
  ".git", ".tox", ".venv", "__pycache__", ".*", "build", "dist", "reports", "services.d", ".md"
]

[lint.isort]
known-first-party = ["bb8_core"]
combine-as-imports = true
force-single-line = false
