# Home Assistant webhook-based sensors for macOS mount telemetry
# Add to configuration.yaml

# Webhook automation to receive telemetry
automation:
  - alias: "MacBook HA Mount Telemetry Webhook"
    id: "macbook_ha_mount_telemetry_webhook"
    trigger:
      - trigger: webhook
        webhook_id: !secret macbook_hass_mount_webhook_id
        allowed_methods:
          - POST
        local_only: true
    action:
      - event: macbook_mount_telemetry_received
        event_data:
          state: "{{ trigger.json.state }}"
          mounted: "{{ trigger.json.mounted }}"
          write_ok: "{{ trigger.json.write_ok }}"
          config_present: "{{ trigger.json.config_present }}"
          keychain_ok: "{{ trigger.json.keychain_ok }}"
          agent_loaded: "{{ trigger.json.agent_loaded }}"
          agent_state: "{{ trigger.json.agent_state }}"
          agent_exit_code: "{{ trigger.json.agent_exit_code }}"
          host: "{{ trigger.json.host }}"
          user: "{{ trigger.json.user }}"
          last_run: "{{ trigger.json.last_run }}"
          age_s: "{{ trigger.json.age_s }}"
          mount_details: "{{ trigger.json.mount_details }}"
  # Alert automations
  - alias: "MacBook HA Mount Down Alert"
    id: "macbook_ha_mount_down_alert"
    mode: restart
    trigger:
      - trigger: state
        entity_id: binary_sensor.macbook_ha_mount
        to: "off"
        for: "00:05:00"
    action:
      - action: persistent_notification.create
        data:
          title: "MacBook HA Mount DOWN"
          message: >
            MacBook Home Assistant mount has been offline for 5+ minutes.
            Last status: {{ states('sensor.macbook_ha_mount_status') }}
            Details: {{ state_attr('sensor.macbook_ha_mount_status', 'mount_details') }}
          notification_id: "macbook_mount_down"

  - alias: "MacBook HA Mount Recovery"
    id: "macbook_ha_mount_recovery"
    mode: restart
    trigger:
      - trigger: state
        entity_id: binary_sensor.macbook_ha_mount
        to: "on"
    action:
      - action: persistent_notification.dismiss
        data:
          notification_id: "macbook_mount_down"
      - action: persistent_notification.create
        data:
          title: "MacBook HA Mount RECOVERED"
          message: >
            MacBook Home Assistant mount is back online.
            Mount details: {{ state_attr('sensor.macbook_ha_mount_status', 'mount_details') }}
            Last run: {{ state_attr('sensor.macbook_ha_mount_status', 'last_run') }}
          notification_id: "macbook_mount_recovery"
# File sensor fallback for mount health
# NOTE: The File integration must be created via the Home Assistant UI (Integrations -> Add Integration -> File).
# The following shows the three UI fields you need to set when creating the File sensor (do NOT add a file platform sensor entry in YAML):
#
# - File path: /config/hestia/config/diagnostics/.last_mount_status.json
# - Value template:
# {{ value_json.health.summary | default('unknown') if value_json is defined else 'unknown' }}
# {{ value_json.health.summary if value_json is defined and value_json.health is defined else 'unknown' }}
# - Unit of measurement: (leave empty or use a short label, e.g. "status")
#
# Additional attributes (if you want them) can be created using a separate Template Sensor or in the UI templates:
# Example Template Sensor (YAML or UI template) to surface attributes from the JSON file content:
# template:
#   - sensor:
#       - name: "Macbook HASS Mount Health Attributes"
#         state: "{{ (states('sensor.macbook_hass_mount_health') | default('unknown')) }}"
#         attributes:
#           mounted: "{{ (value_json_from_file.mount.mounted | default(false)) }}"
#           write_ok: "{{ (value_json_from_file.mount.write_ok | default(false)) }}"
#

template:
  - sensor:
      - name: "Macbook HASS Mount Health Attributes"
        state: >
          {{ states('sensor.macbook_hass_mount_health') | default('unknown') }}
        attributes:
          mounted: >
            {{ (state_attr('sensor.macbook_hass_mount_health','mounted') | default(false)) }}
          write_ok: >
            {{ (state_attr('sensor.macbook_hass_mount_health','write_ok') | default(false)) }}
          agent_state: >
            {{ (state_attr('sensor.macbook_hass_mount_health','agent_state') | default('unknown')) }}
          last_update: >
            {{ (state_attr('sensor.macbook_hass_mount_health','last_update') | default('never')) }}
          upstream_sources: >
            {{ ['sensor.file_last_mount_status_json'] | tojson }}
          downstream_consumers: >
            {{ ['sensor.macbook_ha_mount_status', 'binary_sensor.macbook_ha_mount'] | tojson }}
          file: "/config/packages/hestia/ha_mount_telemetry_webhook.yaml"
          date: "2025-01-04"
          subsystem: "hades"
          integration: "macbook"
          role: "diagnostics"
          module: "hass mount"
          type: "file sensor"
          tier: "μ"
          canonical_id: "macbook_hass_mount_health_μ"

  # Template sensors triggered by webhook events
  - trigger:
      - trigger: event
        event_type: macbook_mount_telemetry_received
      # Periodic refresh to mark the sensor OFF if telemetry is stale
      - trigger: time_pattern
        minutes: "/2"
    sensor:
      - name: "MacBook HA Mount Status"
        unique_id: "macbook_ha_mount_status"
        state: >
          {% if trigger.platform == 'event' %}
            {{ trigger.event.data.state }}
          {% else %}
            {# On time ticks, compute freshness from last_run and force OFF if stale #}
            {% set lr = as_datetime(state_attr('sensor.macbook_ha_mount_status','last_run')) %}
            {% set age = (now() - lr).total_seconds() if lr else 999999 %}
            {{ 'ON' if age < 300 else 'OFF' }}
          {% endif %}
        icon: "mdi:harddisk-plus"
        attributes:
          mounted: "{{ trigger.event.data.mounted | bool }}"
          write_ok: "{{ trigger.event.data.write_ok | bool }}"
          config_present: "{{ trigger.event.data.config_present | bool }}"
          keychain_ok: "{{ trigger.event.data.keychain_ok | bool }}"
          agent_loaded: "{{ trigger.event.data.agent_loaded | bool }}"
          agent_state: "{{ trigger.event.data.agent_state }}"
          agent_exit_code: "{{ trigger.event.data.agent_exit_code | int }}"
          host: "{{ trigger.event.data.host }}"
          user: "{{ trigger.event.data.user }}"
          last_run: "{{ trigger.event.data.last_run }}"
          age_s: "{{ trigger.event.data.age_s | int }}"
          mount_details: "{{ trigger.event.data.mount_details }}"

  - trigger:
      - trigger: event
        event_type: macbook_mount_telemetry_received
      # Periodic refresh to mark the sensor OFF if telemetry is stale
      - trigger: time_pattern
        minutes: "/2"
    binary_sensor:
      - name: "MacBook HA Mount"
        unique_id: "macbook_ha_mount"
        state: >
          {% if trigger.platform == 'event' %}
            {{ trigger.event.data.state == 'ON' }}
          {% else %}
            {# On time ticks, compute freshness from last_run and force OFF if stale #}
            {% set lr = as_datetime(state_attr('sensor.macbook_ha_mount_status','last_run')) %}
            {% set age = (now() - lr).total_seconds() if lr else 999999 %}
            {% set fresh = age < 300 %}
            {{ fresh and states('sensor.macbook_ha_mount_status') == 'ON' }}
          {% endif %}
        device_class: connectivity
        icon: "mdi:harddisk-plus"
