network:
  hosts:
    - id: ha_host
      hostname: homeassistant
      tailscale_hostname: homeassistant.reverse-beta.ts.net
      lan_ip: 192.168.0.1
      tailscale_ip: 100.105.130.99
      services:
        - name: home_assistant_ui
          protocol: http
          port: 8123
        - name: smb_share
          protocol: smb
          ports: [445, 139]

    - id: synology_ds220plus
      hostname: DS220plus
      services:
        - name: smb_share
          protocol: smb
          ports: [445, 139]

  network_metadata:
    cidrs:
      tailscale_cgnat: 100.64.0.0/10
      home_lan: 192.168.0.0/16
