automation:
  - alias: Linked Entities — Kitchen → Laundry (one-way)
    id: link_kitchen_to_laundry
    initial_state: "on"
    mode: restart
    trigger:
      - platform: state
        entity_id: light.group_kitchen_lights
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target: { entity_id: light.group_laundry_room_lights }
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: light.turn_off
                target: { entity_id: light.group_laundry_room_lights }
