automation:
  - alias: Motion Lights — Bedroom
    id: motion_lights_bedroom
    description: Motion-driven; AL handles brightness/CT; presence never gates. Subarea proxy is already folded into bedroom_motion_beta.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: hestia/library/blueprints/sensor-light.yaml
      input:
        ambient_lux_entity: sensor.bedroom_illuminance_beta
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_bedroom
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.bedroom_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.adaptive_bedroom_light_group
        timeout_seconds: "{{ state_attr('var.motion_profile_bedroom','timeout_seconds') | int(120) }}"
        transition_seconds: 0.3
