automation:
  - alias: Motion Lights — Kitchen
    id: motion_lights_kitchen
    description: Main area; AL handles brightness/CT; presence never gates.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        bypass_entity: binary_sensor.motion_bypass_kitchen
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.kitchen_motion_beta
          - binary_sensor.kitchen_occupancy_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:

        timeout_seconds: "{{ state_attr('var.motion_profile_kitchen','timeout_seconds') | int(300) }}"
        transition_seconds: 0.3
---
automation:
  - alias: Motion Lights — Kitchen
    id: motion_lights_kitchen
    description: Kitchen main area; motion-only beta; AL decides photometrics.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        ambient_lux_entity: ""
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_kitchen
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.kitchen_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.al_adaptive_kitchen_light_group
#          - light.kitchen_ceiling_alpha
#          - light.kitchen_cupboards_lightstrip_alpha
#          - light.laundry_ceiling_alpha
        timeout_seconds: "{{ state_attr('var.motion_profile_kitchen','timeout_seconds') | int(300) }}"
        transition_seconds: 0.3
