automation:
  - alias: Motion Lights — Hallway Downstairs
    id: motion_lights_hallway_downstairs
    description: Transit lighting; short timeout; includes Entrance proxy and Upstairs recent proxy.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        bypass_entity: binary_sensor.motion_bypass_hallway_downstairs
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.hallway_downstairs_motion_beta
          - binary_sensor.entrance_motion_proxy
          - binary_sensor.hallway_upstairs_motion_recent_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:

        timeout_seconds: "{{ state_attr('var.motion_profile_hallway_downstairs','timeout_seconds') | int(90) }}"
        transition_seconds: 0.3

  - alias: Motion Lights — Hallway Upstairs
    id: motion_lights_hallway_upstairs
    description: Transit lighting with downstairs propagation via existing recent-motion proxy; AL handles brightness/CT.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        bypass_entity: binary_sensor.motion_bypass_hallway_upstairs
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.hallway_upstairs_motion_beta
          - binary_sensor.hallway_downstairs_motion_recent_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.downstairs_lightstrip_alpha
          - light.hallway_lightstrip_alpha
        timeout_seconds: "{{ state_attr('var.motion_profile_hallway_upstairs','timeout_seconds') | int(90) }}"
        transition_seconds: 0.3


---
automation:
  - alias: Motion Lights — Hallway Downstairs
    id: motion_lights_hallway_downstairs
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        ambient_lux_entity: ""
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_hallway_downstairs
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.hallway_downstairs_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.group_hallway_lights_downstairs
#          - light.downstairs_lightstrip_alpha
#          - light.hallway_lightstrip_alpha          
        timeout_seconds: "{{ state_attr('var.motion_profile_hallway_downstairs','timeout_seconds') | int(90) }}"
        transition_seconds: 0.3

  - alias: Motion Lights — Hallway Upstairs
    id: motion_lights_hallway_upstairs
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        ambient_lux_entity: ""
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_hallway_upstairs
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.hallway_upstairs_motion_beta
          - binary_sensor.hallway_downstairs_motion_recent_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.group_hallway_lights_upstairs
#          - light.upstairs_lightstrip_alpha
#          - light.hallway_lightstrip_alpha
        timeout_seconds: "{{ state_attr('var.motion_profile_hallway_upstairs','timeout_seconds') | int(90) }}"
        transition_seconds: 0.3
