automation:
  - alias: Motion Lights — Desk
    id: motion_lights_desk
    description: Task lighting; strict motion only; AL decides photometrics.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        ambient_lux_entity: sensor.bedroom_illuminance_beta
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_desk
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.desk_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: ""
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.al_adaptive_desk_light_group
#          - light.bedroom_desk_alpha_matter
#          - light.bedroom_desk_corner_alpha
#          - light.bedroom_desk_lightstrip_alpha_matter
#          - light.bedroom_desk_wall_alpha_matter
        timeout_seconds: "{{ state_attr('var.motion_profile_desk','timeout_seconds') | int(300) }}"
        transition_seconds: 0.3