automation:
  - alias: Motion Lights — Ensuite
    id: motion_lights_ensuite
    description: Privacy-aware timing; motion-only beta; AL decides photometrics.
    initial_state: "on"
    max_exceeded: silent
    mode: restart
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        ambient_lux_entity: sensor.ensuite_illuminance_beta
        ambient_lux_threshold: 10
        bypass_entity: binary_sensor.motion_bypass_ensuite
        inhibit_on_startup_seconds: 10
        motion_sensors:
          - binary_sensor.ensuite_motion_beta
        night_mode_brightness_pct: 12
        night_mode_color_temp_mired: 420
        night_mode_enabled: true
        night_mode_sun_elevation: -6
        only_if_lights_off: false
        presence_entity: binary_sensor.ensuite_presence_beta
        require_presence_for_activation: false
        require_sun_condition: false
        restore_state_after_restart: true
        sun_max_elevation: 20
        sun_min_elevation: -12
        target_lights:
          - light.group_ensuite_lights
#          - light.ensuite_accent_alpha
#          - light.ensuite_main_alpha_matter        
#          - light.ensuite_lightstrip_alpha_matter
        timeout_seconds: "{{ state_attr('var.motion_profile_ensuite','timeout_seconds') | int(240) }}"
        transition_seconds: 0.3
