# AML — Telemetry stamping for last_triggered (both motion-based and light-based)

# A) Motion-based stamps (captures intent even if light didn't turn on)
automation:
  - alias: AML Telemetry — Motion (Bedroom)
    id: aml_telemetry_motion_bedroom
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.bedroom_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Desk)
    id: aml_telemetry_motion_desk
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.desk_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.desk_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Ensuite)
    id: aml_telemetry_motion_ensuite
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.ensuite_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.ensuite_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Kitchen)
    id: aml_telemetry_motion_kitchen
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.kitchen_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Hallway Downstairs)
    id: aml_telemetry_motion_hallway_downstairs
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_downstairs_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.hallway_downstairs_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Hallway Upstairs)
    id: aml_telemetry_motion_hallway_upstairs
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_upstairs_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.hallway_upstairs_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Ottoman)
    id: aml_telemetry_motion_ottoman
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_ottoman_motion_proxy
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.ottoman_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

  - alias: AML Telemetry — Motion (Wardrobe)
    id: aml_telemetry_motion_wardrobe
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.wardrobe_motion_beta
        from: "off"
        to: "on"
    action:
      - service: var.set
        data:
          entity_id: var.wardrobe_aml_config
          attributes:
            last_triggered: "{{ now().isoformat() }}"

# B) Light-group ON stamps (confirms actual activation)
  - alias: AML Telemetry — Light ON (Groups)
    id: aml_telemetry_light_on_groups
    initial_state: "on"
    mode: parallel
    trigger:
      - platform: state
        entity_id:
          - light.adaptive_bedroom_light_group
          - light.adaptive_desk_light_group
          - light.group_ensuite_lights
          - light.adaptive_kitchen_light_group
          - light.group_hallway_lights_downstairs
          - light.group_hallway_lights_upstairs
          - light.group_ottoman_light
          - light.group_wardrobe_light
        to: "on"
    variables:
      map: >-
        {{ {
          'light.adaptive_bedroom_light_group': 'var.bedroom_aml_config',
          'light.adaptive_desk_light_group':    'var.desk_aml_config',
          'light.group_ensuite_lights':         'var.ensuite_aml_config',
          'light.adaptive_kitchen_light_group': 'var.kitchen_aml_config',
          'light.group_hallway_lights_downstairs': 'var.hallway_downstairs_aml_config',
          'light.group_hallway_lights_upstairs': 'var.hallway_upstairs_aml_config',
          'light.group_ottoman_light':          'var.ottoman_aml_config',
          'light.group_wardrobe_light':         'var.wardrobe_aml_config'
        } }}
      target_var: "{{ map.get(trigger.entity_id, '') }}"
    condition: "{{ target_var != '' }}"
    action:
      - service: var.set
        data:
          entity_id: "{{ target_var }}"
          attributes:
            last_triggered: "{{ now().isoformat() }}"
