---
hello_world:
  module: hello
  class: HelloWorld
room_db_updater:
  module: room_db_updater
  class: RoomDbUpdater
  db_path: /config/room_database.db
  schema_expected: 1
  canonical_mapping_file: /config/www/area_mapping.yaml
  allowed_domains: ["motion_lighting","vacuum_control","shared","activity_tracking"]
  max_config_size_bytes: 4096
  write_rate_limit_seconds: 5
  dry_run: false
valetudo_default_activity:
  module: valetudo_default_activity
  class: ValetudoDefaultActivity
  ha:
    room_db_update_service: rest_command.room_db_update_config
    room_configs_sensor: sensor.room_configs_vacuum_control
    presence_sensors_glob: _presence_beta
    schedule_entity: schedule.valetudo_allowed
    mapping_path: /config/www/area_mapping.yaml
    base_topic_entity: input_text.valetudo_base_topic
  policy:
    batch_size: 2
    require_presence_clear: true
    optimistic_writeback: true
    optimistic_job_seconds: 90
    rate_limit_seconds: 2
activity_tracker:
  module: activity_tracker
  class: ActivityTracker
  room_db_update_service: rest_command.room_db_update_config
  rate_limit_seconds: 2
room_db_exporter:
  module: room_db_exporter
  class: RoomDbExporter
  db_path: /config/room_database.db
  export_path: /config/room_db_export.json
