name: ADR-0001 Add-on Gate
on:
  push:
  pull_request:

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enforce Add-on–only Topology (ADR-0001 v3)
        shell: bash
        run: |
          set -euo pipefail
          FAIL=0

          echo "== Add-on MUST-HAVE at repo root =="
          for p in app bb8_core services.d config.yaml Dockerfile Makefile README.md VERSION apparmor.txt; do
            [ -e "$p" ] || { echo "::error::missing required: $p"; FAIL=1; }
          done

          echo "== Add-on OPTIONAL (warn-only) =="
          [ -d tests ] || echo "::warning::tests/ not present (optional)"
          [ -d tools ] || echo "::warning::tools/ not present (optional)"
          [ -d .devcontainer ] || echo "::warning::.devcontainer/ not present (optional)"

          echo "== MUST-NOT (workspace-only or recursion) =="
          for p in docs ops reports scripts .githooks .github _backup _backups addon; do
            if [ -e "$p" ]; then echo "::error::forbidden in add-on repo root: $p"; FAIL=1; fi
          done

          echo "== Hygiene =="
          for p in .venv .pytest_cache .ruff_cache .mypy_cache; do
            [ ! -e "$p" ] || { echo "::error::forbidden cache at root: $p"; FAIL=1; }
          done
          if find . -type l | grep -q .; then echo "::error::symlinks are forbidden"; FAIL=1; fi

          if [ $FAIL -eq 0 ]; then
            echo "STRUCTURE_OK — add-on repo"
          else
            exit 1
          fi
