# ═══════════════════════════════════════════════════════════════
# ▶ AUTOMATION: Broadlink Command Triggers ◀
# repurpose physical IR remote keys (N, A, H, Play) as fast
# HDMI Matrix source selectors using Broadlink
# Loader: !include_dir_merge_list from domain/automations/
# Tier: δ  •  Domain: logic  •  Created: 2025-08-23
# ═══════════════════════════════════════════════════════════════

automation:
  - alias: "URC 7935 – Shortcut: Apple TV (N)"
    description: "Align matrix to Apple TV when 'N' is pressed on URC 7935"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: remote
          service: send_command
          service_data:
            device: ofa_urc_7935_streamer
            command: spare_n
    action:
      - service: logbook.log
        data:
          name: "URC 7935"
          message: "N key pressed – Routing to Apple TV (a_1 + b_1)"
      - service: input_text.set_value
        target:
          entity_id: input_text.urc_7935_last_command
        data:
          value: "N → Apple TV"
      - service: script.bedroom_matrix_select_source
        data:
          source: "Apple TV"
          turn_on_tv: true

  - alias: "URC 7935 – Shortcut: Playstation 4 (A)"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: remote
          service: send_command
          service_data:
            device: ofa_urc_7935_streamer
            command: spare_3
    action:
      - service: logbook.log
        data:
          name: "URC 7935"
          message: "A key pressed – Routing to Playstation 4 (a_2 + b_3)"
      - service: input_text.set_value
        target:
          entity_id: input_text.urc_7935_last_command
        data:
          value: "A → Playstation 4"
      - service: script.bedroom_matrix_select_source
        data:
          source: "Playstation 4"
          turn_on_tv: true

  - alias: "URC 7935 – Shortcut: Nintendo Switch (H)"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: remote
          service: send_command
          service_data:
            device: ofa_urc_7935_streamer
            command: spare_h
    action:
      - service: logbook.log
        data:
          name: "URC 7935"
          message: "H key pressed – Routing to Nintendo Switch (a_2 + b_2)"
      - service: input_text.set_value
        target:
          entity_id: input_text.urc_7935_last_command
        data:
          value: "H → Nintendo Switch"
      - service: script.bedroom_matrix_select_source
        data:
          source: "Nintendo Switch"
          turn_on_tv: true

  - alias: "URC 7935 – Shortcut: Nintendo Wii (Play)"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: remote
          service: send_command
          service_data:
            device: ofa_urc_7935_streamer
            command: spare_play
    action:
      - service: logbook.log
        data:
          name: "URC 7935"
          message: "Play key pressed – Routing to Nintendo Wii (a_4 + b_4)"
      - service: input_text.set_value
        target:
          entity_id: input_text.urc_7935_last_command
        data:
          value: "Play → Nintendo Wii"
      - service: script.bedroom_matrix_select_source
        data:
          source: "Nintendo Wii"
          turn_on_tv: true
