---
# Storage: Samba/SMB
# Canonicalized Samba manifest. Replace placeholders with real values
# and create vault entries for credentials. Do not store plaintext passwords here.
name: samba
description: |
  Canonical Samba/SMB configuration manifest. This document is the machine-
  consumable representation of Samba global settings and individual shares.
  Use the `apply_strategos` preview tooling to render a linted `smb.conf` for
  validation (`hestia/tools/apply_strategos/apply_strategos_05_samba_preview.py`).
tags:
  - storage
  - samba

global:
  # Typical keys mapped from smb.conf [global]
  workgroup: WORKGROUP
  server_string: "Hestia Samba"
  log_level: 1
  interfaces: "192.168.0.0/24"
  # Note: apply_strategos lint forbids hardening keys in preview (e.g. hosts allow)

shares:
  - name: config_share
    path: /config
    browseable: true
    read_only: false
    guest_ok: false
    valid_users:
      - homeassistant
    credentials: "vault://hestia/samba/config_share#credentials"
    comment: "Home Assistant configuration (read/write for HA user)"

  - name: media
    path: /mnt/data/media
    browseable: true
    read_only: false
    guest_ok: false
    valid_users:
      - media_user
    credentials: "vault://hestia/samba/media#credentials"
    comment: "Media library share (restrict by user/group)"

  - name: backups
    path: /mnt/backups
    browseable: true
    read_only: false
    guest_ok: false
    valid_users:
      - backup_user
    credentials: "vault://hestia/samba/backups#credentials"
    comment: "Backup destination for selected systems"

notes: |
  - To generate a preview `smb.conf` run the apply_strategos preview which
    expects a Samba overlay document with `global` and `shares` keys (the
    same shape as this YAML). The preview writes `preview/smb.conf` and a
    lint result in `notes/SAMBA_LINT.json`.
  - Create vault entries referenced by the `vault://` URIs. See Vault
    guidance below for naming suggestions and content shape.

vault_guidance:
  naming_convention: |
    Recommended vault URI form: vault://hestia/samba/<share>#credentials
    - Each entry should contain an object with at least `username` and
      `password` keys. Optional fields: `smbpasswd`, `samba_extra_opts`.
  example:
    share: config_share
    uri: vault://hestia/samba/config_share#credentials
    payload: |
      username: homeassistant
      password: <opaque-secret-storage>
---
# Storage: Samba/SMB
# Source of truth: TODO: map to actual smb.conf or the Home Assistant Samba add-on config.
name: samba
description: |
  Placeholder Samba storage configuration. Replace with canonical fields for
  shares, permissions, allowed_hosts, and vault-references to credentials.
tags:
  - storage
  - placeholder
todo: |
  - Inventory current shares under /etc/samba or the HA Samba add-on.
  - Migrate share definitions to this YAML and reference secrets in the vault.
