---
# Diagnostics: Glances integration
# Purpose: Placeholder for glances exporter/REST sensor configuration used by HA.
name: glances
description: |
  Placeholder YAML for the Glances diagnostics integration. Replace with a
  canonical mapping or a small adapter that exposes Glances metrics to the
  diagnostics system.
tags:
  - diagnostics
  - glances
  - placeholder
integration:
  enabled: false
  source: null
todo: |
  - Wire this to existing rest_glances sensors or the Glances add-on config.
  - Provide mapping of metrics to diagnostics probes and thresholds.
