# File: /config/hestia/binary_sensors/beta_motion_recent.yaml
# Description: β-tier motion recent sensors with delay_off logic (Phase 2)
# Refactored: 2025-06-05 - Replaced input_boolean watchdogs with delay_off templates
# Version: 2.0

- platform: template
  sensors:
    bedroom_motion_recent_beta:
      friendly_name: 'Bedroom Motion Recent (Beta)'
      unique_id: 'bedroom_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.bedroom_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'bedroom_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.bedroom_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.bedroom_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.bedroom_occupancy_beta',
            'sensor.bedroom_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    kitchen_motion_recent_beta:
      friendly_name: 'Kitchen Motion Recent (Beta)'
      unique_id: 'kitchen_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.kitchen_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'kitchen_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.kitchen_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.kitchen_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.kitchen_occupancy_beta',
            'sensor.kitchen_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    living_room_motion_recent_beta:
      friendly_name: 'Living Room Motion Recent (Beta)'
      unique_id: 'living_room_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.living_room_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'living_room_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.living_room_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.living_room_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.living_room_occupancy_beta',
            'sensor.living_room_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    ensuite_motion_recent_beta:
      friendly_name: 'Ensuite Motion Recent (Beta)'
      unique_id: 'ensuite_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.ensuite_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'ensuite_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.ensuite_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.ensuite_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.ensuite_occupancy_beta',
            'sensor.ensuite_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    hallway_downstairs_motion_recent_beta:
      friendly_name: 'Hallway Downstairs Motion Recent (Beta)'
      unique_id: 'hallway_downstairs_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.hallway_downstairs_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'hallway_downstairs_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.hallway_downstairs_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.hallway_downstairs_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.hallway_downstairs_occupancy_beta',
            'sensor.hallway_downstairs_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    hallway_upstairs_motion_recent_beta:
      friendly_name: 'Hallway Upstairs Motion Recent (Beta)'
      unique_id: 'hallway_upstairs_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 5
      value_template: >
        {{ is_state('binary_sensor.hallway_upstairs_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'hallway_upstairs_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.hallway_upstairs_motion_beta'
        delay_duration: '300s'
        timeout_behavior: 'delay_off'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.hallway_upstairs_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.hallway_upstairs_occupancy_beta',
            'sensor.hallway_upstairs_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    entrance_motion_recent_beta:
      friendly_name: 'Entrance Motion Recent (Beta)'
      unique_id: 'entrance_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 3
      value_template: >
        {{ is_state('binary_sensor.entrance_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'entrance_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.entrance_motion_beta'
        delay_duration: '180s'
        timeout_behavior: 'delay_off'
        timeout_note: 'Shorter timeout for high-traffic entrance area'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.entrance_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.entrance_occupancy_beta',
            'sensor.entrance_motion_score_gamma'
          ] | tojson }}
        version: '2.0'
        last_updated: '2025-06-05'

    wardrobe_motion_recent_beta:
      friendly_name: 'Wardrobe Motion Recent (Beta)'
      unique_id: 'wardrobe_motion_recent_beta'
      device_class: motion
      delay_off:
        minutes: 2
      value_template: >
        {{ is_state('binary_sensor.wardrobe_motion_beta', 'on') }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'wardrobe_motion_recent_β'
        subsystem: 'hermes'
        module: 'motion'
        type: 'delay_proxy'
        role: 'motion_timeout'
        file: '/config/hestia/binary_sensors/beta_motion_recent.yaml'
        origin: 'binary_sensor.wardrobe_motion_beta'
        delay_duration: '120s'
        timeout_behavior: 'delay_off'
        timeout_note: 'Shorter timeout for utility space with brief interactions'
        refactor_note: 'Phase 2: Replaced input_boolean watchdog with delay_off'
        upstream_source: 'binary_sensor.wardrobe_motion_beta'
        downstream_consumers: >
          {{ [
            'binary_sensor.wardrobe_occupancy_beta',
            'sensor.wardrobe_motion_score_gamma'
          ] | tojson }}
        parent_room: 'bedroom'
        room_area: 'wardrobe'
        version: '2.0'
        last_updated: '2025-06-05'
