# File: /config/hestia/binary_sensors/beta_occupancy_fusion.yaml
# Description: β-tier occupancy sensors with preference-based protocol fusion (Phase 3)
# Refactored: 2025-06-05 - Differentiated occupancy (β) vs presence (γ) layers
# Version: 3.0.0

- platform: template
  sensors:
    bedroom_occupancy_beta:
      friendly_name: 'Bedroom Occupancy (Beta)'
      unique_id: 'bedroom_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          # legacy_id: binary_sensor.bedroom_wardrobe_occupancy_wifi_tplink_alpha, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.bedroom_wardrobe_presence_omega_motion', 'protocol': 'wifi', 'preference': 4, 'type': 'motion'},
          {'entity': 'binary_sensor.wardrobe_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'occupancy'},
          # legacy_id: binary_sensor.withings_sleep_analyzer_in_bed, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.evert_health_biometrics_in_bed', 'protocol': 'wifi', 'preference': 3, 'type': 'occupancy'},
          # legacy_id: binary_sensor.bedroom_occupancy_alpha, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.bedroom_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'bedroom_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'fusion_proxy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'preference_based_fusion'
        protocols: 'Zigbee(1)'
        refactor_note: 'Phase 3: Occupancy fusion layer, distinct from presence inference'
        upstream_sources: >
          {% set sources = [
            # legacy_id: binary_sensor.bedroom_wardrobe_occupancy_wifi_tplink_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.bedroom_wardrobe_presence_omega_motion', 'protocol': 'wifi', 'preference': 4, 'type': 'motion'},
            {'entity': 'binary_sensor.wardrobe_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'occupancy'},
            # legacy_id: binary_sensor.withings_sleep_analyzer_in_bed, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.evert_health_biometrics_in_bed', 'protocol': 'wifi', 'preference': 3, 'type': 'occupancy'},
            # legacy_id: binary_sensor.bedroom_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.bedroom_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'preference-based occupancy signal selection'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            # legacy_id: binary_sensor.bedroom_wardrobe_occupancy_wifi_tplink_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.bedroom_wardrobe_presence_omega_motion', 'protocol': 'wifi', 'preference': 4, 'type': 'motion'},
            {'entity': 'binary_sensor.wardrobe_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'hybrid'},
            # legacy_id: binary_sensor.withings_sleep_analyzer_in_bed, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.evert_health_biometrics_in_bed', 'protocol': 'wifi', 'preference': 3, 'type': 'occupancy'},
            # legacy_id: binary_sensor.bedroom_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.bedroom_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '1'
        downstream_consumers: >
          {{ [
            'binary_sensor.bedroom_presence_gamma',
            'sensor.bedroom_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'

    kitchen_occupancy_beta:
      friendly_name: 'Kitchen Occupancy (Beta)'
      unique_id: 'kitchen_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          # legacy_id: binary_sensor.kitchen_occupancy_alpha, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.kitchen_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'},
          {'entity': 'binary_sensor.kitchen_occupancy_matter_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'hybrid'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'kitchen_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'fusion_proxy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'preference_based_fusion'
        protocols: 'Zigbee(1), Matter(2)'
        refactor_note: 'Phase 3: Zigbee occupancy preferred, Matter hybrid fallback'
        upstream_sources: >
          {% set sources = [
            # legacy_id: binary_sensor.kitchen_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.kitchen_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'},
            {'entity': 'binary_sensor.kitchen_occupancy_matter_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'hybrid'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'preference-based occupancy with hybrid fallback'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            # legacy_id: binary_sensor.kitchen_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.kitchen_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'},
            {'entity': 'binary_sensor.kitchen_occupancy_matter_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'hybrid'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '2'
        downstream_consumers: >
          {{ [
            'binary_sensor.kitchen_presence_gamma',
            'sensor.kitchen_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'

    living_room_occupancy_beta:
      friendly_name: 'Living Room Occupancy (Beta)'
      unique_id: 'living_room_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          # legacy_id: binary_sensor.living_room_occupancy_alpha, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.living_room_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'living_room_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'fusion_proxy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'preference_based_fusion'
        protocols: 'Zigbee(1)'
        refactor_note: 'Phase 3: Single Zigbee occupancy source with extensible pattern'
        upstream_sources: >
          {% set sources = [
            # legacy_id: binary_sensor.living_room_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.living_room_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'single-source zigbee occupancy'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            # legacy_id: binary_sensor.living_room_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.living_room_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '1'
        downstream_consumers: >
          {{ [
            'binary_sensor.living_room_presence_gamma',
            'sensor.living_room_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'

    ensuite_occupancy_beta:
      friendly_name: 'Ensuite Occupancy (Beta)'
      unique_id: 'ensuite_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          # legacy_id: binary_sensor.ensuite_occupancy_alpha, match_type: derived_via_canonical_id
          {'entity': 'binary_sensor.ensuite_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'ensuite_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'fusion_proxy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'preference_based_fusion'
        protocols: 'Zigbee(1)'
        refactor_note: 'Phase 3: Single Zigbee occupancy source with extensible pattern'
        upstream_sources: >
          {% set sources = [
            # legacy_id: binary_sensor.ensuite_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.ensuite_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'single-source zigbee occupancy'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            # legacy_id: binary_sensor.ensuite_occupancy_alpha, match_type: derived_via_canonical_id
            {'entity': 'binary_sensor.ensuite_occupancy_omega_occupancy', 'protocol': 'mqtt', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '1'
        downstream_consumers: >
          {{ [
            'binary_sensor.ensuite_presence_gamma',
            'sensor.ensuite_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'

    hallway_downstairs_occupancy_beta:
      friendly_name: 'Hallway Downstairs Occupancy (Beta)'
      unique_id: 'hallway_downstairs_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          {'entity': 'binary_sensor.hallway_downstairs_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 1, 'type': 'occupancy'}
          {'entity': 'binary_sensor.hallway_entrance_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'occupancy'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'hallway_downstairs_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'occupancy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'occupancy'
        protocols: 'Matter(1)'
        refactor_note: 'Phase 3: Motion-derived occupancy for hallway transition zone'
        upstream_sources: >
          {% set sources = [
            {'entity': 'binary_sensor.hallway_downstairs_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 1, 'type': 'occupancy'}
            {'entity': 'binary_sensor.hallway_entrance_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'occupancy'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'single-source zigbee occupancy'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            {'entity': 'binary_sensor.hallway_downstairs_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 1, 'type': 'occupancy'}
            {'entity': 'binary_sensor.hallway_entrance_occupancy_mtr_alpha', 'protocol': 'matter', 'preference': 2, 'type': 'occupancy'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '1'
        downstream_consumers: >
          {{ [
            'binary_sensor.hallway_downstairs_presence_gamma',
            'sensor.hallway_downstairs_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'

    hallway_upstairs_occupancy_beta:
      friendly_name: 'Hallway Upstairs Occupancy (Beta)'
      unique_id: 'hallway_upstairs_occupancy_beta'
      device_class: occupancy
      value_template: >
        {% from 'template.library.jinja' import preference_select %}
        {% set sources = [
          {'entity': 'binary_sensor.hallway_upstairs_occupancy_matter_alpha', 'protocol': 'Matter', 'preference': 1, 'type': 'occupancy'}
        ] %}
        {{ preference_select(sources) }}
      attribute_templates:
        tier: 'β'
        canonical_id: 'hallway_upstairs_occupancy_β'
        subsystem: 'hermes'
        module: 'occupancy'
        type: 'fusion_proxy'
        role: 'beta_occupancy'
        file: '/config/hestia/binary_sensors/beta_occupancy_fusion.yaml'
        origin: 'motion_derived_occupancy'
        protocols: 'Derived(1)'
        refactor_note: 'Phase 3: Motion-derived occupancy for hallway transition zone'
        upstream_sources: >
          {% set sources = [
            {'entity': 'binary_sensor.hallway_upstairs_occupancy_matter_alpha', 'protocol': 'Matter', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ sources | tojson }}
        aggregation_strategy: 'motion-based occupancy inference'
        active_source: >
          {% from 'template.library.jinja' import get_active_source %}
          {% set sources = [
            {'entity': 'binary_sensor.hallway_upstairs_occupancy_matter_alpha', 'protocol': 'Matter', 'preference': 1, 'type': 'occupancy'}
          ] %}
          {{ get_active_source(sources) }}
        source_count: '1'
        downstream_consumers: >
          {{ [
            'binary_sensor.hallway_upstairs_presence_gamma',
            'sensor.hallway_upstairs_occupancy_decay_delta'
          ] | tojson }}
        version: '3.0.0'
        last_updated: '2025-06-05'
