#═══════════════════════════════════════════════════════════════
# ▶ LIGHTS: Adaptive Light Groups ◀
# Loader: !include_dir_merge_named domain/lights/adaptive_light_groups.yaml
# Schema: group
#═══════════════════════════════════════════════════════════════

- platform: group
  name: "Adaptive Bedroom Light Group"
  unique_id: "7F8E9D2A3B4C5E6F1"
  entities:
    - light.bedroom_accent_alpha
    - light.bedroom_wall_alpha
    - light.bedroom_main_alpha_matter
    - light.bedroom_nightstand_left_alpha_matter
    - light.bedroom_nightstand_right_alpha_matter

- platform: group
  name: "Adaptive Desk Light Group"
  unique_id: "A9B8C7D6E5F4A3B2C"
  entities:
    - light.bedroom_desk_corner_alpha
    - light.bedroom_desk_alpha_matter
    - light.bedroom_desk_lightstrip_alpha_matter
    - light.bedroom_desk_wall_alpha_matter

- platform: group
  name: "Adaptive Kitchen Light Group"
  unique_id: "3F7E8A9B2C4D5E6F7"
  entities:
    - light.kitchen_ceiling_alpha
    - light.kitchen_cupboards_lightstrip_alpha
    - light.laundry_ceiling_alpha

- platform: group
  name: "Adaptive Living Room Light Group"
  unique_id: "8D6F4A2E9C1B7E5A3"
  entities:
    - light.living_room_desk_alpha_matter
    - light.living_room_floorlamp_alpha_matter
    - light.living_room_foxy_alpha_matter
    - light.living_room_main_alpha_matter
    - light.living_room_side_alpha_matter

- platform: group
  name: "Adaptive Ensuite Light Group"
  unique_id: "B5A7E3F9D2C8A4B6E"
  entities:
    - light.ensuite_accent_alpha
    - light.ensuite_main_alpha_matter
    - light.ensuite_lightstrip_alpha_matter

- platform: group
  name: "Adaptive Downstairs Light Group"
  unique_id: "6E9A4F2D8C5B7A3E1"
  entities:
    - light.downstairs_lightstrip_alpha
    - light.hallway_lightstrip_alpha

- platform: group
  name: "Adaptive Upstairs Light Group"
  unique_id: "D4B8F1E6A9C3E7B2F"
  entities:
    - light.upstairs_lightstrip_alpha
    - light.hallway_lightstrip_alpha