---
#═══════════════════════════════════════════════════════════════
# ▶ LIGHTS: Adaptive Light Groups ◀
# Loader: !include_dir_merge_named domain/lights/adaptive_light_groups.yaml
# Schema: group
#═══════════════════════════════════════════════════════════════

- platform: group
  name: "(AL) - Adaptive Bedroom Light Group"
  unique_id: "002A9B6C1E6E4F4R5"
  entities:
    - light.bedroom_accent_alpha
    - light.bedroom_main_alpha
    - light.bedroom_main_alpha_matter
    - light.bedroom_wall_alpha
    - light.bedroom_nightstand_left_alpha
    - light.bedroom_nightstand_left_alpha_matter
    - light.bedroom_nightstand_right_alpha
    - light.bedroom_nightstand_right_alpha_matter

- platform: group
  name: "(AL) - Adaptive Desk Light Group"
  unique_id: "00ALD7A1B502F823H"
  entities:
    - light.bedroom_desk_alpha
    - light.bedroom_desk_alpha_matter
    - light.bedroom_desk_corner_alpha
    - light.bedroom_desk_lightstrip_alpha
    - light.bedroom_desk_lightstrip_alpha_matter
    - light.bedroom_desk_wall_alpha
    - light.bedroom_desk_wall_alpha_matter

- platform: group
  name: "(AL) - Adaptive Kitchen Light Group"
  unique_id: "0002D3E4FQA60702"
  entities:
    - light.kitchen_ceiling_alpha
    - light.kitchen_cupboards_lightstrip_alpha
    - light.laundry_ceiling_alpha