---
#═══════════════════════════════════════════════════════════════
# ▶ LIGHTS: Grouped Bedroom Lights ◀
# Loader: !include_dir_merge_named domain/lights/bedroom_lights.yaml
# Schema: group
# Notes:
# - Includes both *_alpha and *_alpha_matter where applicable.
# - Wall panels & BB-8 entities are excluded per prior directive.
#═══════════════════════════════════════════════════════════════

- platform: group
  name: "Group - All Bedroom Lights"
  unique_id: "7F3A9B2C1D6E4F8G"
  entities:
    - light.bedroom_accent_alpha
    - light.bedroom_hifi_accent_alpha
    - light.bedroom_main_alpha
    - light.bedroom_main_alpha_matter
    - light.bedroom_entrance_alpha
    - light.bedroom_entrance_alpha_matter
    - light.bedroom_mirror_lightstrip_alpha
    - light.bedroom_wall_alpha
    - light.bedroom_nightstand_left_alpha
    - light.bedroom_nightstand_left_alpha_matter
    - light.bedroom_nightstand_right_alpha
    - light.bedroom_nightstand_right_alpha_matter
    - light.bedroom_ottoman_lightstrip_alpha
    - light.bedroom_ottoman_lightstrip_alpha_matter

    - light.bedroom_desk_alpha
    - light.bedroom_desk_alpha_matter
    - light.bedroom_desk_corner_alpha
    - light.bedroom_desk_lightstrip_alpha
    - light.bedroom_desk_lightstrip_alpha_matter
    - light.bedroom_desk_wall_alpha
    - light.bedroom_desk_wall_alpha_matter
    - light.monitor_backlight_alpha # grouped device; segments omitted intentionally

- platform: group
  name: "Group - Main Bedroom Lights"
  unique_id: "2B8E6C4D1A9F7G3H"
  entities:
    - light.bedroom_accent_alpha
    - light.bedroom_hifi_accent_alpha
    - light.bedroom_main_alpha
    - light.bedroom_main_alpha_matter
    - light.bedroom_entrance_alpha
    - light.bedroom_entrance_alpha_matter
    - light.bedroom_mirror_lightstrip_alpha
    - light.bedroom_wall_alpha

- platform: group
  name: "Group - Bedroom Nightstand Lights"
  unique_id: "5D1F9A3B7C2E8G4H"
  entities:
    - light.bedroom_nightstand_left_alpha
    - light.bedroom_nightstand_left_alpha_matter
    - light.bedroom_nightstand_right_alpha
    - light.bedroom_nightstand_right_alpha_matter

- platform: group
  name: "Group - Desk Lights"
  unique_id: "9C3E7A1B5D2F8G4H"
  entities:
    - light.bedroom_desk_alpha
    - light.bedroom_desk_alpha_matter
    - light.bedroom_desk_corner_alpha
    - light.bedroom_desk_lightstrip_alpha
    - light.bedroom_desk_lightstrip_alpha_matter
    - light.bedroom_desk_wall_alpha
    - light.bedroom_desk_wall_alpha_matter
    - light.monitor_backlight_alpha

- platform: group
  name: "Group - Wardrobe Light"
  unique_id: "4A7E2C9B1D5F8G3H"
  entities:
    - light.bedroom_wardrobe_lightstrip_alpha

- platform: group
  name: "Group - Bedroom Utility Lights"
  unique_id: "8F2C7A1B3D5E9G4H"
  entities:
    - light.bedroom_ottoman_lightstrip_alpha
    - light.bedroom_ottoman_lightstrip_alpha_matter
    - light.bedroom_wardrobe_lightstrip_alpha
