---
#═══════════════════════════════════════════════════════════════
# ▶ LIGHTS: Grouped Lights — Other Rooms ◀
# Loader: !include_dir_merge_list domain/lights/other_rooms_lights.yaml
# Domain: light
# Platform: group
# Notes:
# - Include both *_alpha and *_alpha_matter when both exist.
# - Corrected IDs: laundry_ceiling_alpha; removed *_omega in hallway.
#═══════════════════════════════════════════════════════════════

# ── Ensuite ───────────────────────────────────────────────────
- platform: group
  name: "Group - Ensuite Lights"
  unique_id: "A1B2C3D4E5F60701"
  entities:
    - light.ensuite_accent_alpha
    - light.ensuite_main_alpha
    - light.ensuite_main_alpha_matter
    - light.ensuite_lightstrip_tplink_alpha
    - light.ensuite_lightstrip_alpha_matter

# ── Kitchen ───────────────────────────────────────────────────
- platform: group
  name: "Group - Kitchen Lights"
  unique_id: "B1C2D3E4F5A60702"
  entities:
    - light.kitchen_ceiling_alpha
    - light.kitchen_cupboards_lightstrip_alpha

# ── Laundry Room ──────────────────────────────────────────────
- platform: group
  name: "Group - Laundry Room Lights"
  unique_id: "C1D2E3F4A5B60703"
  entities:
    - light.laundry_ceiling_alpha

# ── Living Room (All) ────────────────────────────────────────
- platform: group
  name: "Group - Living Room Lights (All)"
  unique_id: "D1E2F3A4B5C60704"
  entities:
    # Alpha
    - light.living_room_desk_alpha
    - light.living_room_floorlamp_alpha
    - light.living_room_foxy_alpha
    - light.living_room_main_alpha
    - light.living_room_side_alpha
    # Matter (standardised *_alpha_matter)
    - light.living_room_desk_alpha_matter
    - light.living_room_floorlamp_alpha_matter
    - light.living_room_foxy_alpha_matter
    - light.living_room_main_alpha_matter
    - light.living_room_side_alpha_matter
    # Note: stringlights kept out of “All” per your draft; see Switch Lights group

# ── Hallway (All floors) ─────────────────────────────────────
- platform: group
  name: "Group - Hallway Lights (All)"
  unique_id: "E1F2A3B4C5D60705"
  entities:
    - light.downstairs_lightstrip_alpha
    - light.hallway_lightstrip_alpha
    - light.upstairs_lightstrip_alpha

# ── Hallway (Downstairs) ─────────────────────────────────────
- platform: group
  name: "Group - Hallway Lights (Downstairs)"
  unique_id: "E1F2A3B4C5D60706"
  entities:
    - light.downstairs_lightstrip_alpha
    - light.hallway_lightstrip_alpha

# ── Hallway (Upstairs) ───────────────────────────────────────
- platform: group
  name: "Group - Hallway Lights (Upstairs)"
  unique_id: "E1F2A3B4C5D60707"
  entities:
    - light.upstairs_lightstrip_alpha

# ── Switch-controlled Extras ──────────────────────────────────
- platform: group
  name: "Group - Switch Lights"
  unique_id: "F1A2B3C4D5E60708"
  entities:
    - light.kitchen_cupboards_lightstrip_alpha
    - light.living_room_stringlights_alpha
