---
# ══════════════════════════════════════════════════════════════════
# ⟫⟫ LOCALTUYA  •  Additional helpers for Probreeze Dehumidifier ◀
# ⟫⟫ configuration.yaml  •  packages: !include_dir_named packages
# ⟫⟫ Tier: β  •  Domain: configuration  •  Created: 2025-09-04
# ══════════════════════════════════════════════════════════════════

template:
  - binary_sensor:
      - name: "Bedroom Dehumidifier Fault"
        unique_id: bedroom_dehumidifier_fault_active
        device_class: problem
        state: >
          {{ (states('sensor.bedroom_dehumidifier_fault_code') | int(0)) != 0 }}
        attributes:
          raw_code: "{{ states('sensor.bedroom_dehumidifier_fault_code') }}"

automation:
  - alias: "Dehumidifier filter reset → auto off"
    id: a2f7c1e4-8b3d-4e6a-9f2c-7d1e5b4a2c8f
    trigger:
      - platform: state
        entity_id: switch.bedroom_dehumidifier_filter_reset
        to: "on"
    action:
      - delay: "00:00:02"
      - service: switch.turn_off
        target:
          entity_id: switch.bedroom_dehumidifier_filter_reset

  - alias: "Dehumidifier runtime reset → auto off"
    id: c5e9d3b7-2a1f-4c8e-b6d4-3f7a9e2b1d6c
    trigger:
      - platform: state
        entity_id: switch.bedroom_dehumidifier_runtime_reset
        to: "on"
    action:
      - delay: "00:00:02"
      - service: switch.turn_off
        target:
          entity_id: switch.bedroom_dehumidifier_runtime_reset
