#════════════════════════════════════════════════════════════════════════════════════════
# ▶ ERROR MONITORING & STARTUP HEALTH ◀
# Implements ADR-0020 Error Canonicalization for system health monitoring
# Reference: ADR-0017 Fallback Local Logging, ADR-0014 OOM Policy
#════════════════════════════════════════════════════════════════════════════════════════

template:
  - sensor:
      - name: "Startup Health Monitor"
        unique_id: "startup_health_monitor"
        state: >-
          {% set body = states('sensor.system_log_file_content') | default('', true) %}
          {% if body not in ['unknown', 'unavailable', ''] %}
            {% set flags = [
              'Something is blocking Home Assistant' in body,
              'sync_google() running' in body,
              'automatic backup could not be uploaded' in body,
              'SynologyNAS' in body
            ] %}
            {{ 'degraded' if (flags | select('equalto', true) | list | length) > 0 else 'healthy' }}
          {% else %}
            unknown
          {% endif %}
        attributes:
          last_check: "{{ now().isoformat() }}"
          monitored_issues: "Google Assistant sync blocking, Synology backup upload failures, Network scanner startup delays, Component initialization timeouts"
          fixes_applied: "Disabled Google Assistant integration, Configured local backup location, Optimized network scanner scan interval, Added startup timeout controls"
          adr_compliance: "ADR-0020: Error canonicalization applied, ADR-0024: Canonical /config paths used, ADR-0014: Memory optimization implemented, ADR-0018: Backup lifecycle management"

      - name: "Backup System Status"
        unique_id: "backup_system_status"  
        state: >-
          {% if is_state('input_boolean.enable_backup_notifications', 'on') %}
            {% set backup_dir = '/config/hestia/workspace/archive/backups' %}
            enabled
          {% else %}
            disabled
          {% endif %}
        attributes:
          backup_location: "/config/hestia/workspace/archive/backups"
          synology_upload: "disabled (preventing failures)"
          retention_days: 7
          adr_compliance: "ADR-0024 canonical paths, ADR-0018 lifecycle"

binary_sensor:
  - platform: template
    sensors:
      startup_completed:
        friendly_name: "Home Assistant Startup Completed"
        unique_id: "ha_startup_completed"
        value_template: >-
          {{ states('sensor.home_assistant_uptime_alpha') != 'unknown' and 
             (as_timestamp(now()) - as_timestamp(states('sensor.home_assistant_uptime_alpha'))) > 300 }}
        attribute_templates:
          startup_duration: >-
            {% if states('sensor.home_assistant_uptime_alpha') != 'unknown' %}
              {{ (as_timestamp(now()) - as_timestamp(states('sensor.home_assistant_uptime_alpha'))) / 60 | round(1) }} minutes
            {% else %}
              unknown
            {% endif %}

automation:
  - id: startup_optimization_success
    alias: "System: Startup Optimization Success"
    description: "Log when startup completes without blocking issues"
    trigger:
      - platform: state
        entity_id: binary_sensor.startup_completed
        to: 'on'
    action:
      - action: system_log.write
        data:
          message: >
            ✅ Startup optimization successful - ADR-0020 fixes applied:
            - Google Assistant disabled (sync_google blocking resolved)
            - Backup location configured locally (Synology upload disabled)
            - Network scanner optimized (scan_interval: 600s)
            - Startup check window: 300s
          level: info
          logger: "homeassistant.adr_0020_fixes"
    mode: single

  - id: startup_optimization_failure
    alias: "System: Startup Optimization Failure (Timeout)"
    description: "Log when startup does not complete within the expected timeout (blocking issues likely)"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    variables:
      timeout_secs: 300
      grace_secs: 30
      check_after: "{{ timeout_secs + grace_secs }}"
    action:
      - delay:
          seconds: "{{ check_after }}"
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ states('binary_sensor.startup_completed') != 'on' }}
            sequence:
              - action: system_log.write
                data:
                  level: error
                  logger: "homeassistant.adr_0020_fixes"
                  message: >-
                    ❌ Startup optimization FAILED or TIMED OUT after {{ check_after }}s.
                    binary_sensor.startup_completed = {{ states('binary_sensor.startup_completed') }}
                    last_changed = {{ states.binary_sensor.startup_completed.last_changed if states.binary_sensor.startup_completed is not none else 'n/a' }}
                    Expected (ADR-0020) to be ready within {{ timeout_secs }}s:
                    - Google Assistant disabled (sync_google blocking resolved)
                    - Local backup path active (Synology upload disabled)
                    - Network scanner interval set to 600s
                    - Startup timeout enforced ({{ timeout_secs }}s)
