# ══════════════════════════════════════════════════════════════════
# ▶ OOM GUARD • Persistent notice when memory is high for 5 minutes
# File: packages/oom_guard.yaml
# Tier: γ  •  Domain: automation  •  Created: 2025-09-19
# Updated: 2025-09-30 - Canonical merged version
# Notes:
# - Do NOT configure `platform: systemmonitor` here. Add the integration via UI.
# - This automation watches `sensor.system_monitor_memory_usage` provided by System Monitor.
# - Includes automatic clearing notification when usage returns to normal.
# - Uses numeric_state triggers for better performance than template triggers.
# ══════════════════════════════════════════════════════════════════

template:
  - sensor:
      - name: "oom_memory_use_percent"
        unique_id: "oom_memory_use_percent"
        unit_of_measurement: "%"
        state: "{{ states('sensor.system_monitor_memory_usage') | float(0) }}"
        availability: >-
          {{ states('sensor.system_monitor_memory_usage') not in ['unknown','unavailable','none',''] }}

input_number:
  oom_threshold_percent:
    name: OOM threshold (%)
    min: 50
    max: 99
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:memory
    initial: 90

automation:
  - id: oom_notice_when_high_5min
    alias: "OOM: persistent notice when memory high for 5m"
    mode: restart
    triggers:
      # Use numeric_state for better performance than template trigger
      - trigger: numeric_state
        entity_id: sensor.system_monitor_memory_usage
        above: input_number.oom_threshold_percent
        for: "00:05:00"
    conditions: []
    actions:
      - alias: "Notify of high memory"
        action: persistent_notification.create
        data:
          notification_id: "oom_memory_alert"
          title: "High Memory Use"
          message: >-
            Memory has been above {{ states('input_number.oom_threshold_percent') | int }}%
            for 5 minutes.
            Current: {{ (states('sensor.system_monitor_memory_usage') | float(0)) | round(1) }}%.
            Check add-ons/integrations (DB size, media indexers, diagnostics).

  - id: oom_clear_notice_when_memory_normal
    alias: "OOM: clear persistent notice when memory normal"
    mode: single
    triggers:
      # Clear notification when memory drops below threshold
      - trigger: numeric_state
        entity_id: sensor.system_monitor_memory_usage
        below: input_number.oom_threshold_percent
    conditions: []
    actions:
      - alias: "Clear OOM notification"
        action: persistent_notification.dismiss
        data:
          notification_id: "oom_memory_alert"
