rest:
  - resource: http://192.168.0.104:8086/health
    scan_interval: 300
    timeout: 10
    sensor:
      - name: influxdb_health
        value_template: "{{ value_json.status }}"
        json_attributes: [version]    

rest_command:
  influx_write_smoke:
    url: "http://192.168.0.104:8086/api/v2/write?org=Hestia&bucket=homeassistant&precision=ns"
    method: POST
    headers:
      Authorization: !secret influxdb_header   # <- guardrail-compliant
      Content-Type: "text/plain"
    payload: >
      ha_smoketest,host=homeassistant value=1i {{ (now().timestamp() * 1000000000) | int }}

automation:
  - id: influx_smoke_on_start
    alias: Influx smoke on HA start
    mode: single
    trigger: [{ platform: homeassistant, event: start }]
    action: [{ service: rest_command.influx_write_smoke }]
