# ══════════════════════════════════════════════════════════════════
# ▶ OOM GUARD • Persistent notice when memory is high for 5 minutes
# File: packages/oom_guard.yaml
# Tier: γ  •  Domain: automation  •  Created: 2025-09-19
# Notes:
# - Do NOT configure `platform: systemmonitor` here. Add the integration via UI.
# - This automation watches `sensor.system_monitor_memory_usage` provided by System Monitor.
# - Includes a clearing notification when usage returns to normal.
# ══════════════════════════════════════════════════════════════════

template:
  - sensor:
      - name: "oom_memory_use_percent"
        unique_id: "oom_memory_use_percent"
        unit_of_measurement: "%"
        state: "{{ states('sensor.system_monitor_memory_usage') | float(0) }}"
        availability: "{{ states('sensor.system_monitor_memory_usage') not in ['unknown','unavailable','none',''] }}"

input_number:
  oom_threshold_percent:
    name: OOM threshold (%)
    min: 50
    max: 99
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:memory
    initial: 90

automation:
  - id: oom_notice_when_high_5min
    alias: "OOM: persistent notice when memory high for 5m"
    mode: restart
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.system_monitor_memory_usage') | float(0) >
             states('input_number.oom_threshold_percent') | float(0) }}
        for: "00:05:00"
    condition: []
    action:
      - alias: "Notify of high memory"
        type: call_service
        domain: persistent_notification
        service: create
        data:
          notification_id: "oom_memory_alert"
          title: "High Memory Use"
          message: >-
            Memory has been above {{ states('input_number.oom_threshold_percent') | int }}%
            for 5 minutes.
            Current: {{ (states('sensor.system_monitor_memory_usage') | float(0)) | round(1) }}%.
            Check add-ons/integrations (DB size, media indexers, diagnostics).

  - id: oom_clear_notice_when_memory_normal
    alias: "OOM: clear persistent notice when memory normal"
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.system_monitor_memory_usage') | float(0) <
             states('input_number.oom_threshold_percent') | float(0) }}
    condition: []
    action:
      - alias: "Clear OOM notification"
        type: call_service
        domain: persistent_notification
        service: dismiss
        data:
          notification_id: "oom_memory_alert"
