#════════════════════════════════════════════════════════════════════════════════════════
# ▶ BACKUP CONFIGURATION (ADR-0024 Compliant) ◀
# Implements backup location management following canonical path policy
# Reference: ADR-0018 Workspace Lifecycle Policy, ADR-0024 Canonical Config Path
#════════════════════════════════════════════════════════════════════════════════════════

# Configuration for Home Assistant backup system
# Uses local filesystem locations per ADR-0024 canonical path requirements

homeassistant:
  # Backup configuration using canonical paths
  # Disables problematic remote upload locations that were causing failures
  backup:
    # Use local backup directory following ADR-0024 canonical structure
    # Location: /config/hestia/workspace/archive/backups (per hestia_structure.md)
    location: "/config/hestia/workspace/archive/backups"
    
    # Retention policy per ADR-0018 lifecycle management
    keep_days: 7
    
    # Disable automatic upload to problematic Synology location
    # This prevents the "SynologyNAS" upload failures reported in logs
    auto_upload: false

# Alternative: If Synology integration backup is needed, use automation approach
# This provides better error handling and follows ADR-0020 error patterns
automation:
  - id: backup_to_synology_controlled
    alias: "Backup: Synology Upload (Controlled)"
    description: "Upload backups to Synology with proper error handling"
    trigger:
      - platform: event
        event_type: backup_end
        event_data:
          success: true
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.success == true }}"
    action:
      - service: notify.persistent_notification
        data:
          title: "Backup Available"
          message: >
            Backup {{ trigger.event.data.backup_id }} completed successfully.
            File location: {{ trigger.event.data.backup_path }}
            Size: {{ (trigger.event.data.size / 1024 / 1024) | round(1) }} MB
          notification_id: "backup_completed"
    mode: single
    
# Input boolean to control backup behavior
input_boolean:
  enable_backup_notifications:
    name: "Enable Backup Notifications"
    initial: true
    icon: mdi:backup-restore
