---
# ══════════════════════════════════════════════════════════════════
# ⟫⟫ SPHERO BB-8  •  Every Boy's Best Bud ◀
# ⟫⟫ configuration.yaml  •  packages: !include_dir_named integrations
# ⟫⟫ Tier: awesome  •  Domain: amazing  •  Created: 2025-06-16
# ══════════════════════════════════════════════════════════════════

automation:
  - alias: "BB-8 Not Available Notification"
    trigger:
      - trigger: state
        entity_id: binary_sensor.bb8_presence
        to: "off"
    action:
      - action: persistent_notification.create
        data:
          title: "BB-8 Not Available"
          message: >
            BB-8 could not be reached for command execution.
            Please ensure the robot is awake (remove from charger, tap to wake).
  - alias: "BB-8 Error Notification"
    trigger:
      - trigger: state
        entity_id: sensor.bb8_error_state
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != '' }}"
    action:
      - action: persistent_notification.create
        data:
          title: "BB-8 Error"
          message: "{{ states('sensor.bb8_error_state') }}"
  - alias: "BB-8 Heartbeat Lost"
    trigger:
      - trigger: state
        entity_id: sensor.bb8_heartbeat
        to: "offline"
        for: "00:05:00"
    action:
      - action: persistent_notification.create
        data:
          title: "BB-8 Heartbeat Lost"
          message: "No heartbeat received from BB-8 for 5 minutes."

script:
  bb8_roll:
    alias: BB8 Roll
    sequence:
      - action: button.press
        target:
          entity_id: button.bb8_roll
  bb8_stop:
    alias: BB8 Stop
    sequence:
      - action: button.press
        target:
          entity_id: button.bb8_stop
  bb8_led_red:
    alias: BB8 LED Red
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bb8_led
        data:
          rgb_color: [255, 0, 0]
  bb8_led_green:
    alias: BB8 LED Green
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bb8_led
        data:
          rgb_color: [0, 255, 0]
  bb8_led_blue:
    alias: BB8 LED Blue
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bb8_led
        data:
          rgb_color: [0, 0, 255]
  bb8_led_white:
    alias: BB8 LED White
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bb8_led
        data:
          rgb_color: [255, 255, 255]
  bb8_power_on:
    alias: BB8 Power On
    sequence:
      - action: switch.turn_on
        target:
          entity_id: switch.bb8_power
  bb8_power_off:
    alias: BB8 Power Off
    sequence:
      - action: switch.turn_off
        target:
          entity_id: switch.bb8_power
  bb8_diagnostics:
    alias: BB8 Run Diagnostics
    sequence:
      - action: mqtt.publish
        data:
          topic: bb8/command
          payload: '{"command":"diagnostics"}'
