blueprint:
  name: Closet Light Toggle with Door Sensor
  description: Turn on a light when the door opens and turn it off when closed.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: The binary sensor on your closet door
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - door
          multiple: false
    light_entity:
      name: Closet Light
      description: The light to control
      selector:
        entity:
          domain:
          - light
          multiple: false
  source_url: https://raw.githubusercontent.com/Ishai-Revach/ha-blueprints/refs/heads/main/blueprints/automation/Ishai/closet_door_light.yaml
trigger:
- platform: state
  entity_id: !input door_sensor
  to: 'on'
- platform: state
  entity_id: !input door_sensor
  to: 'off'
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input door_sensor
      state: 'on'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_entity
  - conditions:
    - condition: state
      entity_id: !input door_sensor
      state: 'off'
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_entity
