name: ADR Lint

on:
  push:
    paths:
      - 'hestia/docs/ADR/**'
  pull_request:
    paths:
      - 'hestia/docs/ADR/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m venv ~/.venv/hestia-adr
          source ~/.venv/hestia-adr/bin/activate
          pip install -e .[test]
      - name: Run tests
        run: pytest -q
      - name: Run linter
        run: hestia-adr-lint --format json
