# ═══════════════════════════════════════════════════════════════
# ▶ AUTOMATION: Desk Presence Decay Logic ◀
# Handles decay and reset for desk and ethernet presence scores
# Loader: !include_dir_merge_list from domain/automations/
# Tier: δ  •  Domain: logic  •  Last updated: 2025-09-30
# ═══════════════════════════════════════════════════════════════

- alias: "Desk Presence Decay (combined)"
  id: "desk_presence_decay_combined"
  mode: single
  trigger:
    - platform: time_pattern
      seconds: "/10"
  variables:
    items:
      - entity: binary_sensor.desk_presence_inferred
        input: input_number.desk_presence_decay_delta
      - entity: binary_sensor.desk_macbook_recent_connectivity_desk
        input: input_number.desk_presence_ethernet_decay_delta

    decay_rate: 0.2
    reset_value: 10
    floor_value: 0
    epsilon: 0.01
  action:
    - repeat:
        for_each: "{{ items }}"
        sequence:
          - variables:
              entity: "{{ repeat.item.entity }}"
              input:  "{{ repeat.item.input }}"
              valid:  "{{ states(entity) not in ['unavailable','unknown','none'] }}"
              current: "{{ is_state(entity, 'on') if valid else false }}"
              prev:    "{{ states(input) | float(0) }}"
              raw_result: >-
                {{ reset_value if current else (prev - decay_rate) }}
              result: >-
                {{ [raw_result, floor_value] | max | round(1) }}
              delta: "{{ (result - prev) | float }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (delta | abs) > epsilon }}"
                sequence:
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ input }}"
                    data:
                      value: "{{ result }}"